# Generated by Django 4.2.4 on 2023-09-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0002_verification_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='verification_num',
        ),
        migrations.AddField(
            model_name='register_info',
            name='stauts',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register_info',
            name='verification_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='register_info',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
