# Generated by Django 4.2.4 on 2023-09-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0003_delete_verification_num_register_info_stauts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_info',
            name='stauts',
            field=models.IntegerField(default=0),
        ),
    ]
