# Generated by Django 4.2.4 on 2023-09-16 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0004_alter_register_info_stauts'),
    ]

    operations = [
        migrations.CreateModel(
            name='a1c_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('a1c', models.FloatField(null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='blood_pressure_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('systolic', models.FloatField(max_length=30, null=True)),
                ('diastolic', models.FloatField(max_length=30, null=True)),
                ('pulse', models.IntegerField(null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='blood_sugar_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('sugar', models.IntegerField(null=True)),
                ('timeperiod', models.IntegerField(null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='body_weight_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('weight', models.FloatField(max_length=30, null=True)),
                ('body_fat', models.FloatField(max_length=30, null=True)),
                ('bmi', models.FloatField(max_length=30, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='default_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('sugar_delta_max', models.IntegerField(null=True)),
                ('sugar_delta_min', models.IntegerField(null=True)),
                ('sugar_morning_max', models.IntegerField(null=True)),
                ('sugar_morning_min', models.IntegerField(null=True)),
                ('sugar_evening_max', models.IntegerField(null=True)),
                ('sugar_evening_min', models.IntegerField(null=True)),
                ('sugar_before_max', models.IntegerField(null=True)),
                ('sugar_before_min', models.IntegerField(null=True)),
                ('sugar_after_max', models.IntegerField(null=True)),
                ('sugar_after_min', models.IntegerField(null=True)),
                ('systolic_max', models.IntegerField(null=True)),
                ('systolic_min', models.IntegerField(null=True)),
                ('diastolic_max', models.IntegerField(null=True)),
                ('diastolic_min', models.IntegerField(null=True)),
                ('pulse_max', models.IntegerField(null=True)),
                ('pulse_min', models.IntegerField(null=True)),
                ('weight_max', models.IntegerField(null=True)),
                ('weight_min', models.IntegerField(null=True)),
                ('bmi_max', models.IntegerField(null=True)),
                ('bmi_min', models.IntegerField(null=True)),
                ('body_fat_max', models.IntegerField(null=True)),
                ('body_fat_min', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='diet_diary_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('meal', models.IntegerField(null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='drug_used_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('type', models.BooleanField(null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='friend_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('type', models.IntegerField(null=True)),
                ('invite_code', models.CharField(max_length=30, null=True)),
                ('status', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='medical_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('diabetes_type', models.IntegerField(null=True)),
                ('oad', models.BooleanField(null=True)),
                ('insulin', models.BooleanField(null=True)),
                ('anti_hypertensives', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='message_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('message', models.TextField(null=True)),
                ('pushed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='setting_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_recording', models.BooleanField(null=True)),
                ('no_recording_for_a_day', models.BooleanField(null=True)),
                ('over_max_or_under_min', models.BooleanField(null=True)),
                ('after_meal', models.BooleanField(null=True)),
                ('unit_of_sugar', models.BooleanField(null=True)),
                ('unit_of_weight', models.BooleanField(null=True)),
                ('unit_of_height', models.BooleanField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='register_info',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='register_info',
            old_name='stauts',
            new_name='status',
        ),
        migrations.AddField(
            model_name='register_info',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='register_info',
            name='birthday',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='register_info',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_info',
            name='gender',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='register_info',
            name='gender_text',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='register_info',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='register_info',
            name='message',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='register_info',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='register_info',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='register_info',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='register_info',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
