# Generated by Django 4.2.4 on 2023-09-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0006_register_info_weight_setting_info_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default_info',
            name='bmi_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='bmi_min',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='body_fat_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='body_fat_min',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='sugar_after_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='sugar_after_min',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='sugar_before_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='sugar_before_min',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='sugar_delta_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='sugar_delta_min',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='sugar_evening_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='sugar_evening_min',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='sugar_morning_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='sugar_morning_min',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='weight_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='weight_min',
            field=models.FloatField(null=True),
        ),
    ]
