# Generated by Django 4.2.4 on 2023-09-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0007_alter_default_info_bmi_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='default_info',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='setting_info',
            name='user_id',
        ),
    ]
