# Generated by Django 4.2.4 on 2023-09-18 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0008_remove_default_info_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood_pressure_info',
            old_name='user_id',
            new_name='member_id',
        ),
        migrations.RenameField(
            model_name='blood_sugar_info',
            old_name='user_id',
            new_name='member_id',
        ),
        migrations.RenameField(
            model_name='body_weight_info',
            old_name='user_id',
            new_name='member_id',
        ),
    ]
