# Generated by Django 4.2.4 on 2023-09-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0010_remove_blood_pressure_info_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_sugar_info',
            name='sugar',
            field=models.FloatField(null=True),
        ),
    ]
