# Generated by Django 4.2.4 on 2023-09-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0011_alter_blood_sugar_info_sugar'),
    ]

    operations = [
        migrations.CreateModel(
            name='share_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField(null=True)),
                ('type', models.IntegerField(null=True)),
                ('relation_type', models.IntegerField(null=True)),
            ],
        ),
    ]
