# Generated by Django 4.2.4 on 2023-09-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0012_share_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='a1c_info',
            old_name='user_id',
            new_name='member_id',
        ),
        migrations.RenameField(
            model_name='diet_diary_info',
            old_name='user_id',
            new_name='member_id',
        ),
        migrations.RenameField(
            model_name='drug_used_info',
            old_name='user_id',
            new_name='member_id',
        ),
        migrations.RenameField(
            model_name='friend_info',
            old_name='user_id',
            new_name='member_id',
        ),
        migrations.RenameField(
            model_name='medical_info',
            old_name='user_id',
            new_name='member_id',
        ),
        migrations.RenameField(
            model_name='message_text',
            old_name='user_id',
            new_name='member_id',
        ),
    ]
