# Generated by Django 4.2.4 on 2023-09-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0013_rename_user_id_a1c_info_member_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet_diary_info',
            name='image',
            field=models.IntegerField(null=True),
        ),
    ]
