# Generated by Django 4.2.4 on 2023-09-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0014_diet_diary_info_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend_info',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='friend_info',
            name='updated_at',
        ),
    ]
