# Generated by Django 4.2.4 on 2023-09-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0016_alter_a1c_info_a1c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a1c_info',
            name='member_id',
        ),
    ]
