# Generated by Django 4.2.4 on 2023-09-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0018_a1c_info_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug_used_info',
            name='type',
            field=models.IntegerField(null=True),
        ),
    ]
