# Generated by Django 4.2.4 on 2023-09-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0021_register_info_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_info',
            name='message',
        ),
    ]
