# Generated by Django 4.2.4 on 2023-09-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0022_remove_register_info_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_info',
            name='name',
        ),
        migrations.AddField(
            model_name='default_info',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
