# Generated by Django 4.2.4 on 2023-09-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0025_default_info_name_setting_info_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='default_info',
            name='member_id',
            field=models.IntegerField(null=True),
        ),
    ]
