# Generated by Django 4.2.4 on 2023-09-21 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0026_default_info_member_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='vip_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField(null=True)),
                ('level', models.IntegerField(null=True)),
                ('remark', models.FloatField(null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='setting_info',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting_info',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
