# Generated by Django 4.2.4 on 2023-09-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0030_register_info_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField(null=True)),
                ('message', models.TextField(null=True)),
                ('reply_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='message_text',
        ),
    ]
