# Generated by Django 4.2.4 on 2023-09-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0032_alter_medical_info_anti_hypertensives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_info',
            name='anti_hypertensives',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='medical_info',
            name='diabetes_type',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='medical_info',
            name='insulin',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='medical_info',
            name='oad',
            field=models.BooleanField(null=True),
        ),
    ]
