# Generated by Django 4.2.4 on 2023-09-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0033_alter_medical_info_anti_hypertensives_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting_info',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='a1c_info',
            name='a1c',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='a1c_info',
            name='created_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00'),
        ),
        migrations.AlterField(
            model_name='a1c_info',
            name='member_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='a1c_info',
            name='recorded_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00'),
        ),
        migrations.AlterField(
            model_name='a1c_info',
            name='updated_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00'),
        ),
        migrations.AlterField(
            model_name='blood_pressure_info',
            name='diastolic',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blood_pressure_info',
            name='member_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blood_pressure_info',
            name='pulse',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blood_pressure_info',
            name='recorded_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00'),
        ),
        migrations.AlterField(
            model_name='blood_pressure_info',
            name='systolic',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blood_sugar_info',
            name='drug',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blood_sugar_info',
            name='exercise',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blood_sugar_info',
            name='member_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blood_sugar_info',
            name='recorded_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00'),
        ),
        migrations.AlterField(
            model_name='blood_sugar_info',
            name='sugar',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blood_sugar_info',
            name='timeperiod',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='body_weight_info',
            name='bmi',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='body_weight_info',
            name='body_fat',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='body_weight_info',
            name='member_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='body_weight_info',
            name='recorded_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00'),
        ),
        migrations.AlterField(
            model_name='body_weight_info',
            name='weight',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='bmi_max',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='bmi_min',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='body_fat_max',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='body_fat_min',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='diastolic_max',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='diastolic_min',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='member_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='pulse_max',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='pulse_min',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='sugar_after_max',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='sugar_after_min',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='sugar_before_max',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='sugar_before_min',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='sugar_delta_max',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='sugar_delta_min',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='sugar_evening_max',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='sugar_evening_min',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='sugar_morning_max',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='sugar_morning_min',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='systolic_max',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='systolic_min',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='weight_max',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='weight_min',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='diet_diary_info',
            name='description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diet_diary_info',
            name='image',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='diet_diary_info',
            name='lat',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='diet_diary_info',
            name='lng',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='diet_diary_info',
            name='meal',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='diet_diary_info',
            name='member_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='diet_diary_info',
            name='recorded_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00'),
        ),
        migrations.AlterField(
            model_name='diet_diary_info',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diet_diary_info',
            name='type',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='drug_used_info',
            name='member_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='drug_used_info',
            name='name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drug_used_info',
            name='recorded_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00'),
        ),
        migrations.AlterField(
            model_name='drug_used_info',
            name='type',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='friend_info',
            name='invite_code',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='friend_info',
            name='member_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='friend_info',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='friend_info',
            name='type',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medical_info',
            name='anti_hypertensives',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='medical_info',
            name='created_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00'),
        ),
        migrations.AlterField(
            model_name='medical_info',
            name='diabetes_type',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='medical_info',
            name='insulin',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='medical_info',
            name='member_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medical_info',
            name='oad',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='medical_info',
            name='updated_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00'),
        ),
        migrations.AlterField(
            model_name='message_info',
            name='created_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00'),
        ),
        migrations.AlterField(
            model_name='message_info',
            name='member_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='message_info',
            name='message',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='message_info',
            name='reply_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='message_info',
            name='updated_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00'),
        ),
        migrations.AlterField(
            model_name='register_info',
            name='account',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='register_info',
            name='address',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='register_info',
            name='birthday',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='register_info',
            name='created_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00'),
        ),
        migrations.AlterField(
            model_name='register_info',
            name='email',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='register_info',
            name='gender',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='register_info',
            name='gender_text',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='register_info',
            name='height',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='register_info',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='register_info',
            name='name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='register_info',
            name='password',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='register_info',
            name='phone',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='register_info',
            name='status',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='register_info',
            name='verification_code',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='register_info',
            name='weight',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='setting_info',
            name='after_meal',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting_info',
            name='after_recording',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting_info',
            name='name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='setting_info',
            name='no_recording_for_a_day',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting_info',
            name='over_max_or_under_min',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting_info',
            name='unit_of_height',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting_info',
            name='unit_of_sugar',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting_info',
            name='unit_of_weight',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting_info',
            name='updated_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00'),
        ),
        migrations.AlterField(
            model_name='share_info',
            name='member_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='share_info',
            name='relation_type',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='share_info',
            name='type',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='created_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00'),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='ended_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00'),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='level',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='member_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='remark',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='started_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00'),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='updated_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00'),
        ),
    ]
