# Generated by Django 4.2.4 on 2023-09-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0034_remove_setting_info_created_at_alter_a1c_info_a1c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting_info',
            name='member_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
