# Generated by Django 4.2.4 on 2023-09-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0036_alter_medical_info_anti_hypertensives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a1c_info',
            name='a1c',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
