# Generated by Django 4.2.4 on 2023-09-22 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0037_alter_a1c_info_a1c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='a1c_info',
            old_name='member_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='blood_pressure_info',
            old_name='member_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='blood_sugar_info',
            old_name='member_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='body_weight_info',
            old_name='member_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='default_info',
            old_name='member_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='diet_diary_info',
            old_name='member_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='drug_used_info',
            old_name='member_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='friend_info',
            old_name='member_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='medical_info',
            old_name='member_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='message_info',
            old_name='member_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='setting_info',
            old_name='member_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='share_info',
            old_name='member_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='vip_info',
            old_name='member_id',
            new_name='user_id',
        ),
    ]
