# Generated by Django 4.2.4 on 2023-09-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0038_rename_member_id_a1c_info_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_info',
            name='member_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
