# Generated by Django 4.2.4 on 2023-09-22 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0039_message_info_member_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share_info',
            old_name='user_id',
            new_name='share_id',
        ),
    ]
