# Generated by Django 4.2.4 on 2023-09-22 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0040_rename_user_id_share_info_share_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share_info',
            old_name='share_id',
            new_name='user_id',
        ),
    ]
