# Generated by Django 4.2.4 on 2023-09-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0041_rename_share_id_share_info_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet_diary_info',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
