# Generated by Django 4.2.4 on 2023-09-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0043_diet_diary_info_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet_diary_info',
            name='lat',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
