# Generated by Django 4.2.4 on 2023-09-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0045_alter_diet_diary_info_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_info',
            name='pushed_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00'),
        ),
        migrations.AddField(
            model_name='register_info',
            name='updated_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00'),
        ),
    ]
