# Generated by Django 4.2.4 on 2023-09-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0046_register_info_pushed_at_register_info_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_info',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
