# Generated by Django 4.2.4 on 2023-09-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0048_register_info_user_id_alter_register_info_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_info',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
