# Generated by Django 4.2.4 on 2023-09-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0049_alter_register_info_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_info',
            name='group',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
