# Generated by Django 4.2.4 on 2023-09-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0051_remove_friend_info_invite_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='friend_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, null=True)),
                ('type', models.IntegerField(default=0, null=True)),
                ('invite_code', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
    ]
