# Generated by Django 4.2.4 on 2023-09-25 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0052_friend_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='friend_info',
        ),
        migrations.DeleteModel(
            name='friend_list',
        ),
    ]
