# Generated by Django 4.2.4 on 2023-09-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0056_register_info_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_pressure_info',
            name='systolic',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
