# Generated by Django 4.2.4 on 2023-09-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0057_alter_blood_pressure_info_systolic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_pressure_info',
            name='systolic',
            field=models.FloatField(default=0, null=True),
        ),
    ]
