# Generated by Django 4.2.5 on 2023-09-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0058_alter_blood_pressure_info_systolic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_info',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
