# Generated by Django 4.2.5 on 2023-10-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0060_remove_register_info_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='friend_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, null=True)),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('type', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='friend_list',
            old_name='relation_type',
            new_name='type',
        ),
    ]
