# Generated by Django 4.2.5 on 2023-10-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0061_friend_requests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend_list',
            old_name='type',
            new_name='relation_type',
        ),
    ]
