# Generated by Django 4.2.5 on 2023-10-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0063_rename_friend_requests_friends_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends_requests',
            name='read',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='friends_requests',
            name='relation_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='friends_requests',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
