# Generated by Django 4.2.5 on 2023-10-04 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0065_friends_requests_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='default_info',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='setting_info',
            name='user_id',
        ),
    ]
