# Generated by Django 4.2.5 on 2023-10-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0067_remove_default_info_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_info',
            name='anti_hypertensives',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medical_info',
            name='insulin',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medical_info',
            name='oad',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
