# Generated by Django 4.2.5 on 2023-10-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0069_alter_medical_info_anti_hypertensives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_info',
            name='fcm_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
