# Generated by Django 4.2.5 on 2023-10-06 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0074_alter_vip_info_ended_at_alter_vip_info_started_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting_info',
            name='name',
        ),
        migrations.AddField(
            model_name='default_info',
            name='user_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='setting_info',
            name='user_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='ended_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 15, 47, 2, 945845)),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 15, 47, 2, 945845)),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 15, 47, 2, 945845)),
        ),
    ]
