# Generated by Django 4.2.5 on 2023-10-06 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0078_alter_vip_info_created_at_alter_vip_info_ended_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_info',
            name='gender_text',
        ),
        migrations.AlterField(
            model_name='register_info',
            name='group',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 15, 54, 31, 944941)),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='ended_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 15, 54, 31, 944941)),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 15, 54, 31, 944941)),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 15, 54, 31, 944941)),
        ),
    ]
