# Generated by Django 4.2.5 on 2023-10-06 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0088_alter_setting_info_unit_of_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip_info',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 17, 22, 58, 325270)),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='ended_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 17, 22, 58, 325270)),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 17, 22, 58, 325270)),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 17, 22, 58, 325270)),
        ),
    ]
