# Generated by Django 4.2.5 on 2023-10-07 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0107_alter_a1c_info_created_at_alter_a1c_info_recorded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_info',
            name='created_at',
            field=models.DateTimeField(default='2023-10-07 23'),
        ),
        migrations.AlterField(
            model_name='medical_info',
            name='updated_at',
            field=models.DateTimeField(default='2023-10-07 23'),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 7, 23, 53, 15, 614901)),
        ),
    ]
