# Generated by Django 4.2.5 on 2023-10-07 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0108_alter_medical_info_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip_info',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 7, 23, 54, 3, 745581)),
        ),
    ]
