# Generated by Django 4.2.5 on 2023-10-07 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0111_alter_a1c_info_created_at_alter_a1c_info_recorded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_info',
            name='anti_hypertensives',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='medical_info',
            name='diabetes_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medical_info',
            name='insulin',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='medical_info',
            name='oad',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 1, 21, 8, 56781)),
        ),
    ]
