# Generated by Django 4.2.5 on 2023-10-07 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0112_alter_medical_info_anti_hypertensives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_info',
            name='anti_hypertensives',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medical_info',
            name='insulin',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medical_info',
            name='oad',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 1, 33, 10, 93168)),
        ),
    ]
