# Generated by Django 4.2.5 on 2023-10-07 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0113_alter_medical_info_anti_hypertensives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip_info',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 1, 34, 33, 686700)),
        ),
    ]
