# Generated by Django 4.2.5 on 2023-10-07 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0118_alter_vip_info_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip_info',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 1, 59, 24, 875508)),
        ),
    ]
