# Generated by Django 4.2.5 on 2023-10-09 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0120_alter_a1c_info_created_at_alter_a1c_info_recorded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='friends_send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, null=True)),
                ('type', models.IntegerField(default=0, null=True)),
                ('invite_code', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='friend_list',
            old_name='user_id',
            new_name='uid',
        ),
        migrations.AlterField(
            model_name='a1c_info',
            name='created_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='a1c_info',
            name='recorded_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='a1c_info',
            name='updated_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='blood_pressure_info',
            name='recorded_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='blood_sugar_info',
            name='recorded_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='body_weight_info',
            name='recorded_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='created_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='default_info',
            name='updated_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='diet_diary_info',
            name='recorded_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='drug_used_info',
            name='recorded_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='friends_requests',
            name='created_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='friends_requests',
            name='updated_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='medical_info',
            name='created_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='medical_info',
            name='updated_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='message_info',
            name='created_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='message_info',
            name='updated_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='register_info',
            name='created_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='register_info',
            name='pushed_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='register_info',
            name='updated_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='setting_info',
            name='created_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='setting_info',
            name='updated_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='created_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='ended_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='started_at',
            field=models.DateTimeField(default='2023-10-10 01'),
        ),
        migrations.AlterField(
            model_name='vip_info',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 10, 1, 50, 22, 890516)),
        ),
    ]
