# Generated by Django 4.2.5 on 2023-10-09 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puyuan_ap', '0121_friends_send_rename_user_id_friend_list_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip_info',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 10, 1, 50, 30, 859677)),
        ),
    ]
